<a href="https://colab.research.google.com/github/bryaanabraham/deep_learning_and_reinforcement_learning/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
np.random.seed(1234)  ## This ensures we get the same data if all of the other parameters remain fixed

num_obs = 100
x1 = np.random.uniform(0,10,num_obs)
x2 = np.random.uniform(0,10,num_obs)
const = np.ones(num_obs)
eps = np.random.normal(0,.5,num_obs)

#true values:
b = 1.5
theta_1 = 2
theta_2 = 5

y = b*const+ theta_1*x1 + theta_2*x2 + eps

x_mat = np.array([const,x1,x2]).T
print(y)
print()
x_mat

[63.2831419  43.48266445 64.7293531  36.92045639 19.80553091 46.77713411
 21.71525119 49.72714229 26.21126724 18.7091071  58.07409635 22.02858404
 37.14781244 14.94944309 29.51504096 42.17657547 67.34164729 47.16808046
 58.28924847 40.41414156 24.16777345 13.0641513  58.85746237 14.46678125
 30.38622456 28.00669924 37.2942645  32.01007158 43.84511205 61.73970772
 59.86209079 19.41618232 36.80435033 49.29545584 33.41407722 66.55707634
 47.55479892 32.82141771 29.75579241 26.99077357 25.26770218 51.33873237
 28.83205168 47.91695921 32.12176433 21.97779713 43.6813833  17.88156951
 21.55339558 55.27971736  3.34191102 58.42011632 26.50714223 26.80326854
 24.59597421 23.30139255 33.32477121 41.55969333 18.89805544 54.81416996
 22.05650062 54.79789989 31.22647796 50.70879754 18.74235517 16.4101024
 42.09861214 47.65887788 25.3839663  38.38215358 19.26798931 41.20159486
 31.448528   31.81730502 57.83087306 60.15317808 13.51707082 40.19099503
 59.42039393 52.35976968 27.41115225 13.77221471 14.

array([[1.        , 6.9384666 , 9.54565784],
       [1.        , 5.37176673, 6.37483255],
       [1.        , 8.89230083, 9.10849753],
       [1.        , 0.52266426, 6.92136751],
       [1.        , 7.83183701, 0.42942989],
       [1.        , 1.45173269, 8.33586901],
       [1.        , 0.58698426, 3.69948516],
       [1.        , 0.58994581, 9.36557001],
       [1.        , 0.5197123 , 4.83052875],
       [1.        , 5.15986088, 1.25331607],
       [1.        , 4.0499622 , 9.64454184],
       [1.        , 9.99649594, 0.17025831],
       [1.        , 1.08570011, 6.76570765],
       [1.        , 3.27384302, 1.40439966],
       [1.        , 9.97829932, 1.55312853],
       [1.        , 4.01114392, 6.49557747],
       [1.        , 8.83335766, 9.81654216],
       [1.        , 5.69138581, 6.94807415],
       [1.        , 9.5324089 , 7.61973893],
       [1.        , 8.85387244, 4.25209183],
       [1.        , 7.79285592, 1.38893444],
       [1.        , 0.31808063, 2.16186303],
       [1.

In [10]:
# Solve directly using sklearn
from sklearn.linear_model import LinearRegression

lr_model = LinearRegression(fit_intercept=False)
lr_model.fit(x_mat, y)

lr_model.coef_

array([1.4851806 , 1.98354728, 5.00425146])

Setting fit_intercept=False in a linear regression model means that you are explicitly instructing the model not to estimate an intercept term (i.e., the y-intercept) in the linear equation. Instead, the model will assume that the line or hyperplane representing the linear relationship between the independent variables (features) and the dependent variable (target) must pass through the origin (0,0) in the feature space.

In [9]:
#solving using matrix multiplication
np.linalg.inv(np.dot(x_mat.T,x_mat)).dot(x_mat.T).dot(y)

array([1.4851806 , 1.98354728, 5.00425146])